(define (problem composite_prob_1) 
(:domain ipc_composite)
(:objects
	; Depot
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 truck1 - truck-depot
	pallet0 pallet1 pallet2 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 - crate
	hoist0 hoist1 hoist2 - hoist

	; Satellite
	satellite0 - satellite
	instrument0 instrument1 - instrument
	infrared0 infrared1 image2 - mode
	GroundStation1 Star0 GroundStation2 Planet3 Planet4 Phenomenon5 Phenomenon6 Star7 - direction

	; Driverlog
	driver1 driver2 - driver
    truckd1 truckd2 - truck-driverlog
    package1 package2 - obj
    s0 s1 s2 p1-0 p1-2 - location
)

(:init
	; Depot
	(located-at-depot pallet0 depot0)
	(clear crate1)
	(located-at-depot pallet1 distributor0)
	(clear crate4)
	(located-at-depot pallet2 distributor1)
	(clear crate5)
	(located-at-depot truck0 depot0)
	(= (current_load truck0) 0)
	(= (load_limit truck0) 457)
	(located-at-depot truck1 distributor0)
	(= (current_load truck1) 0)
	(= (load_limit truck1) 331)
	(located-at-depot hoist0 depot0)
	(available-depot hoist0)
	(located-at-depot hoist1 distributor0)
	(available-depot hoist1)
	(located-at-depot hoist2 distributor1)
	(available-depot hoist2)
	(located-at-depot crate0 distributor0)
	(on-depot crate0 pallet1)
	(= (weight crate0) 99)
	(located-at-depot crate1 depot0)
	(on-depot crate1 pallet0)
	(= (weight crate1) 89)
	(located-at-depot crate2 distributor1)
	(on-depot crate2 pallet2)
	(= (weight crate2) 67)
	(located-at-depot crate3 distributor0)
	(on-depot crate3 crate0)
	(= (weight crate3) 81)
	(located-at-depot crate4 distributor0)
	(on-depot crate4 crate3)
	(= (weight crate4) 4)
	(located-at-depot crate5 distributor1)
	(on-depot crate5 crate2)
	(= (weight crate5) 50)
	(= (fuel-cost) 0)
; ----------------------------------------------------------------------------
	; Driverlog
	(located-at-driverlog driver1 s2)
    (located-at-driverlog driver2 s2)
    (located-at-driverlog truckd1 s0)
    (empty-driverlog truckd1)
    (located-at-driverlog truckd2 s0)
    (empty-driverlog truckd2)
    (located-at-driverlog package1 s0)
    (located-at-driverlog package2 s0)
    (path s1 p1-0)
    (path p1-0 s1)
    (path s0 p1-0)
    (path p1-0 s0)
    (= (time-to-walk s1 p1-0) 43)
    (= (time-to-walk p1-0 s1) 43)
    (= (time-to-walk s0 p1-0) 80)
    (= (time-to-walk p1-0 s0) 80)
    (path s1 p1-2)
    (path p1-2 s1)
    (path s2 p1-2)
    (path p1-2 s2)
    (= (time-to-walk s1 p1-2) 29)
    (= (time-to-walk p1-2 s1) 29)
    (= (time-to-walk s2 p1-2) 79)
    (= (time-to-walk p1-2 s2) 79)
    (link s0 s1)
    (link s1 s0)
    (= (time-to-drive s0 s1) 70)
    (= (time-to-drive s1 s0) 70)
    (link s0 s2)
    (link s2 s0)
    (= (time-to-drive s0 s2) 47)
    (= (time-to-drive s2 s0) 47)
    (link s2 s1)
    (link s1 s2)
    (= (time-to-drive s2 s1) 24)
    (= (time-to-drive s1 s2) 24)
    (= (driven) 0)
    (= (walked) 0)
; ----------------------------------------------------------------------------
; Satellite
	(supports instrument0 infrared1)
	(supports instrument0 infrared0)
	(calibration_target instrument0 Star0)
	(supports instrument1 image2)
	(supports instrument1 infrared1)
	(supports instrument1 infrared0)
	(calibration_target instrument1 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet4)
	(= (data_capacity satellite0) 1000)
	(= (fuel-satellite satellite0) 129)
	(= (data Planet3 infrared0) 183)
	(= (data Planet4 infrared0) 142)
	(= (data Phenomenon5 infrared0) 26)
	(= (data Phenomenon6 infrared0) 166)
	(= (data Star7 infrared0) 155)
	(= (data Planet3 infrared1) 146)
	(= (data Planet4 infrared1) 99)
	(= (data Phenomenon5 infrared1) 148)
	(= (data Phenomenon6 infrared1) 2)
	(= (data Star7 infrared1) 160)
	(= (data Planet3 image2) 137)
	(= (data Planet4 image2) 184)
	(= (data Phenomenon5 image2) 107)
	(= (data Phenomenon6 image2) 182)
	(= (data Star7 image2) 165)
	(= (slew_time GroundStation1 Star0) 45)
	(= (slew_time Star0 GroundStation1) 45)
	(= (slew_time GroundStation2 Star0) 82)
	(= (slew_time Star0 GroundStation2) 82)
	(= (slew_time GroundStation2 GroundStation1) 42)
	(= (slew_time GroundStation1 GroundStation2) 42)
	(= (slew_time Planet3 Star0) 13)
	(= (slew_time Star0 Planet3) 13)
	(= (slew_time Planet3 GroundStation1) 17)
	(= (slew_time GroundStation1 Planet3) 17)
	(= (slew_time Planet3 GroundStation2) 17)
	(= (slew_time GroundStation2 Planet3) 17)
	(= (slew_time Planet4 Star0) 1)
	(= (slew_time Star0 Planet4) 1)
	(= (slew_time Planet4 GroundStation1) 14)
	(= (slew_time GroundStation1 Planet4) 14)
	(= (slew_time Planet4 GroundStation2) 58)
	(= (slew_time GroundStation2 Planet4) 58)
	(= (slew_time Planet4 Planet3) 30)
	(= (slew_time Planet3 Planet4) 30)
	(= (slew_time Phenomenon5 Star0) 78)
	(= (slew_time Star0 Phenomenon5) 78)
	(= (slew_time Phenomenon5 GroundStation1) 56)
	(= (slew_time GroundStation1 Phenomenon5) 56)
	(= (slew_time Phenomenon5 GroundStation2) 39)
	(= (slew_time GroundStation2 Phenomenon5) 39)
	(= (slew_time Phenomenon5 Planet3) 21)
	(= (slew_time Planet3 Phenomenon5) 21)
	(= (slew_time Phenomenon5 Planet4) 15)
	(= (slew_time Planet4 Phenomenon5) 15)
	(= (slew_time Phenomenon6 Star0) 87)
	(= (slew_time Star0 Phenomenon6) 87)
	(= (slew_time Phenomenon6 GroundStation1) 75)
	(= (slew_time GroundStation1 Phenomenon6) 75)
	(= (slew_time Phenomenon6 GroundStation2) 25)
	(= (slew_time GroundStation2 Phenomenon6) 25)
	(= (slew_time Phenomenon6 Planet3) 26)
	(= (slew_time Planet3 Phenomenon6) 26)
	(= (slew_time Phenomenon6 Planet4) 82)
	(= (slew_time Planet4 Phenomenon6) 82)
	(= (slew_time Phenomenon6 Phenomenon5) 36)
	(= (slew_time Phenomenon5 Phenomenon6) 36)
	(= (slew_time Star7 Star0) 30)
	(= (slew_time Star0 Star7) 30)
	(= (slew_time Star7 GroundStation1) 16)
	(= (slew_time GroundStation1 Star7) 16)
	(= (slew_time Star7 GroundStation2) 50)
	(= (slew_time GroundStation2 Star7) 50)
	(= (slew_time Star7 Planet3) 80)
	(= (slew_time Planet3 Star7) 80)
	(= (slew_time Star7 Planet4) 67)
	(= (slew_time Planet4 Star7) 67)
	(= (slew_time Star7 Phenomenon5) 20)
	(= (slew_time Phenomenon5 Star7) 20)
	(= (slew_time Star7 Phenomenon6) 29)
	(= (slew_time Phenomenon6 Star7) 29)
	(= (data-stored) 0)
	(= (fuel-used) 0)

)

(:goal (and
		; (on-depot crate0 crate1)
		; (on-depot crate1 pallet2)
		; (on-depot crate2 pallet0)
		; (located-at-driverlog truckd2 s0)
	    ; (located-at-driverlog package1 s0)
    	; (located-at-driverlog package2 s0)
		(have_image Planet4 infrared0)
		(have_image Phenomenon5 image2)
		(have_image Phenomenon6 infrared0)
		(have_image Star7 infrared0)
	)
)
)
