(define (problem MINECRAFTCONTRIVED-1)
    (:domain minecraft-contrived)


(:objects
	obsidian0 obsidian1 - obsidian-block
	steve - agent
	old-pointy - diamond-pickaxe
	dmd0 dmd1 dmd2 - diamond
	stick0 stick1 - stick
	flint0 flint1 flint2 - flint
	iron-ore0 - iron-ore
	coal0 - coal
	iron-ingot0 - iron-ingot
	netherportal0 - netherportal
	flint-and-steel0 - flint-and-steel
	rt0 rt1 rt2 rt3 rt4 rt5 rt6 rt7 rt8 - red-tulip
	df0 df1 df2 df3 df4 df5 df6 df7 df8 - daisy-flower
	of0 of1 of2 of3 of4 of5 of6 of7 of8 - orchid-flower
)


(:init
	(agent-alive steve)
	(= (x steve) 0)
	(= (y steve) 0)
	(= (z steve) 0)
	( = ( agent-num-wool steve ) 0 )
	( = ( agent-num-diamond steve ) 0 )
	( = ( agent-num-stick steve ) 0 )
	( = ( agent-num-diamond-pickaxe steve ) 1 )
	( = ( agent-num-apple steve ) 0 )
	( = ( agent-num-potato steve ) 0 )
	( = ( agent-num-rabbit steve ) 0 )
	( = ( agent-num-flint steve ) 0 )
	( = ( agent-num-coal steve ) 0 )
	( = ( agent-num-iron-ore steve ) 0 )
	( = ( agent-num-iron-ingot steve ) 0 )
	( = ( agent-num-flint-and-steel steve ) 0 )
	(= (x obsidian0) 11)
	(= (y obsidian0) 8)
	(= (z obsidian0) 1)
	(= (x obsidian1) 10)
	(= (y obsidian1) 8)
	(= (z obsidian1) 0)
	( = ( block-hits obsidian0 ) 0 )
	( = ( block-hits obsidian1 ) 0 )
	(= (agent-num-obsidian-block steve) 0)
	( = ( item-hits rt0 ) 0 )
	( = ( item-hits rt1 ) 0 )
	( = ( item-hits rt2 ) 0 )
	( = ( item-hits rt3 ) 0 )
	( = ( item-hits rt4 ) 0 )
	( = ( item-hits rt5 ) 0 )
	( = ( item-hits rt6 ) 0 )
	( = ( item-hits rt7 ) 0 )
	( = ( item-hits rt8 ) 0 )
	(= (agent-num-red-tulip steve) 0)
	( = ( item-hits of0 ) 0 )
	( = ( item-hits of1 ) 0 )
	( = ( item-hits of2 ) 0 )
	( = ( item-hits of3 ) 0 )
	( = ( item-hits of4 ) 0 )
	( = ( item-hits of5 ) 0 )
	( = ( item-hits of6 ) 0 )
	( = ( item-hits of7 ) 0 )
	( = ( item-hits of8 ) 0 )
	(= (agent-num-orchid-flower steve) 0)
	( = ( item-hits df0 ) 0 )
	( = ( item-hits df1 ) 0 )
	( = ( item-hits df2 ) 0 )
	( = ( item-hits df3 ) 0 )
	( = ( item-hits df4 ) 0 )
	( = ( item-hits df5 ) 0 )
	( = ( item-hits df6 ) 0 )
	( = ( item-hits df7 ) 0 )
	( = ( item-hits df8 ) 0 )
	(= (agent-num-daisy-flower steve) 0)
	(= (x old-pointy) 0)
	(= (y old-pointy) 0)
	(= (z old-pointy) 0)
	( not ( present old-pointy ) )
	(= (x stick0) 1)
	(= (y stick0) 0)
	(= (z stick0) 0)
	( present stick0 )
	(= (x stick1) 1)
	(= (y stick1) 1)
	(= (z stick1) 0)
	( present stick1 )
	(= (x flint0) 8)
	(= (y flint0) 0)
	(= (z flint0) 0)
	( present flint0 )
	(= (x flint1) 8)
	(= (y flint1) 1)
	(= (z flint1) 0)
	( present flint1 )
	(= (x flint2) 8)
	(= (y flint2) 2)
	(= (z flint2) 0)
	( present flint2 )
	(= (x iron-ore0) 10)
	(= (y iron-ore0) 0)
	(= (z iron-ore0) 0)
	( present iron-ore0 )
	(= (x coal0) 9)
	(= (y coal0) 0)
	(= (z coal0) 0)
	( present coal0 )
	(= (x dmd0) 2)
	(= (y dmd0) 0)
	(= (z dmd0) 0)
	(present dmd0)
	(= (x dmd1) 2)
	(= (y dmd1) 1)
	(= (z dmd1) 0)
	(present dmd1)
	(= (x dmd2) 2)
	(= (y dmd2) 2)
	(= (z dmd2) 0)
	(present dmd2)
	(= (x iron-ingot0) 0)
	(= (y iron-ingot0) 0)
	(= (z iron-ingot0) 0)
	(not ( present iron-ingot0 ))
	(= (x flint-and-steel0) 0)
	(= (y flint-and-steel0) 0)
	(= (z flint-and-steel0) 0)
	(not ( present flint-and-steel0 ))
	(= (x netherportal0) 0)
	(= (y netherportal0) 0)
	(= (z netherportal0) 0)
	(not ( present netherportal0 ))
	(= (x rt0) 6)
	(= (y rt0) 3)
	(= (z rt0) 0)
	( present rt0 )
	(= (x rt1) 6)
	(= (y rt1) 4)
	(= (z rt1) 0)
	( present rt1 )
	(= (x rt2) 6)
	(= (y rt2) 5)
	(= (z rt2) 0)
	( present rt2 )
	(= (x rt3) 7)
	(= (y rt3) 3)
	(= (z rt3) 0)
	( present rt3 )
	(= (x rt4) 7)
	(= (y rt4) 4)
	(= (z rt4) 0)
	( present rt4 )
	(= (x rt5) 7)
	(= (y rt5) 5)
	(= (z rt5) 0)
	( present rt5 )
	(= (x rt6) 8)
	(= (y rt6) 3)
	(= (z rt6) 0)
	( present rt6 )
	(= (x rt7) 8)
	(= (y rt7) 4)
	(= (z rt7) 0)
	( present rt7 )
	(= (x rt8) 8)
	(= (y rt8) 5)
	(= (z rt8) 0)
	( present rt8 )
	(= (x df0) 1)
	(= (y df0) 3)
	(= (z df0) 0)
	( present df0 )
	(= (x df1) 1)
	(= (y df1) 4)
	(= (z df1) 0)
	( present df1 )
	(= (x df2) 1)
	(= (y df2) 5)
	(= (z df2) 0)
	( present df2 )
	(= (x df3) 2)
	(= (y df3) 3)
	(= (z df3) 0)
	( present df3 )
	(= (x df4) 2)
	(= (y df4) 4)
	(= (z df4) 0)
	( present df4 )
	(= (x df5) 2)
	(= (y df5) 5)
	(= (z df5) 0)
	( present df5 )
	(= (x df6) 3)
	(= (y df6) 3)
	(= (z df6) 0)
	( present df6 )
	(= (x df7) 3)
	(= (y df7) 4)
	(= (z df7) 0)
	( present df7 )
	(= (x df8) 3)
	(= (y df8) 5)
	(= (z df8) 0)
	( present df8 )
	(= (x of0) 4)
	(= (y of0) 6)
	(= (z of0) 0)
	( present of0 )
	(= (x of1) 4)
	(= (y of1) 7)
	(= (z of1) 0)
	( present of1 )
	(= (x of2) 4)
	(= (y of2) 8)
	(= (z of2) 0)
	( present of2 )
	(= (x of3) 5)
	(= (y of3) 6)
	(= (z of3) 0)
	( present of3 )
	(= (x of4) 5)
	(= (y of4) 7)
	(= (z of4) 0)
	( present of4 )
	(= (x of5) 5)
	(= (y of5) 8)
	(= (z of5) 0)
	( present of5 )
	(= (x of6) 6)
	(= (y of6) 6)
	(= (z of6) 0)
	( present of6 )
	(= (x of7) 6)
	(= (y of7) 7)
	(= (z of7) 0)
	( present of7 )
	(= (x of8) 6)
	(= (y of8) 8)
	(= (z of8) 0)
	( present of8 )
	(block-present obsidian0)
	(block-present obsidian1)
)


(:goal (and 
                            (present netherportal0)
                            (= (x netherportal0) 11)
                            (= (y netherportal0) 7)
                            (= (z netherportal0) 0)
                          )
        )
        


; State space size if we allow any object to have any z > 17770672208392715482


; Conventional state space size = 1.2052166072939045e+47


)