(define (problem MINECRAFTHUT)
    (:domain minecraft-house)


(:objects
	steve - agent
	old-pointy - diamond-pickaxe
	oak1 oak2 oak3 oak4 oak5 oak6 oak7 oak8 oak9 oak10 oak11 - oak_wood-block
	oak_stairs1 - oak_wood_stairs-block
)


(:init
	(agent-alive steve)
	(= (x steve) 0)
	(= (y steve) 0)
	(= (z steve) 0)
	( = ( agent-num-diamond-pickaxe steve ) 0 )
	(= (x oak1) 1)
	(= (y oak1) 1)
	(= (z oak1) 1)
	( not ( block-present oak1 ) )
	(= (x oak2) 1)
	(= (y oak2) 1)
	(= (z oak2) 1)
	( not ( block-present oak2 ) )
	(= (x oak3) 1)
	(= (y oak3) 1)
	(= (z oak3) 1)
	( not ( block-present oak3 ) )
	(= (x oak4) 1)
	(= (y oak4) 1)
	(= (z oak4) 1)
	( not ( block-present oak4 ) )
	(= (x oak5) 1)
	(= (y oak5) 1)
	(= (z oak5) 1)
	( not ( block-present oak5 ) )
	(= (x oak6) 1)
	(= (y oak6) 1)
	(= (z oak6) 1)
	( not ( block-present oak6 ) )
	(= (x oak7) 1)
	(= (y oak7) 1)
	(= (z oak7) 1)
	( not ( block-present oak7 ) )
	(= (x oak8) 1)
	(= (y oak8) 1)
	(= (z oak8) 1)
	( not ( block-present oak8 ) )
	(= (x oak9) 1)
	(= (y oak9) 1)
	(= (z oak9) 1)
	( not ( block-present oak9 ) )
	(= (x oak10) 1)
	(= (y oak10) 1)
	(= (z oak10) 1)
	( not ( block-present oak10 ) )
	(= (x oak11) 1)
	(= (y oak11) 1)
	(= (z oak11) 1)
	( not ( block-present oak11 ) )
	(= (x oak_stairs1) 1)
	(= (y oak_stairs1) 1)
	(= (z oak_stairs1) 1)
	( not ( block-present oak_stairs1 ) )
	( = ( block-hits oak1 ) 0 )
	( = ( block-hits oak2 ) 0 )
	( = ( block-hits oak3 ) 0 )
	( = ( block-hits oak4 ) 0 )
	( = ( block-hits oak5 ) 0 )
	( = ( block-hits oak6 ) 0 )
	( = ( block-hits oak7 ) 0 )
	( = ( block-hits oak8 ) 0 )
	( = ( block-hits oak9 ) 0 )
	( = ( block-hits oak10 ) 0 )
	( = ( block-hits oak11 ) 0 )
	( = ( block-hits oak_stairs1 ) 0 )
	(= (agent-num-oak_wood-block steve) 48)
	(= (agent-num-oak_wood_stairs-block steve) 1)
	(= (x old-pointy) 0)
	(= (y old-pointy) 0)
	(= (z old-pointy) 0)
	( not ( present old-pointy ) )
)


(:goal (and                
                (block-present oak_stairs1 )
                (= (x oak_stairs1) 2)
                (= (y oak_stairs1) 2)
                (= (z oak_stairs1) 0)
                
                (= (x oak1) 2)
                (= (y oak1) 3)
                (= (z oak1) 0)
                (= (x oak2) 1)
                (= (y oak2) 3)
                (= (z oak2) 0)
                (= (x oak3) 3)
                (= (y oak3) 3)
                (= (z oak3) 0)
                
                (= (x oak4) 2)
                (= (y oak4) 4)
                (= (z oak4) 0)
                (= (x oak5) 1)
                (= (y oak5) 4)
                (= (z oak5) 0)
                (= (x oak6) 3)
                (= (y oak6) 4)
                (= (z oak6) 0)
                (= (x oak7) 4)
                (= (y oak7) 4)
                (= (z oak7) 0)
                (= (x oak8) 0)
                (= (y oak8) 4)
                (= (z oak8) 0)

                (= (x oak9) 2)
                (= (y oak9) 5)
                (= (z oak9) 0)
                (= (x oak10) 1)
                (= (y oak10) 5)
                (= (z oak10) 0)
                (= (x oak11) 3)
                (= (y oak11) 5)
                (= (z oak11) 0)
                
                ))


)